### ISSUE TITLE
Search result pagination missing

### ISSUE THREAD

**Issue by benjamin-dk** [cfdp/ch3#1]
As can be seen on a page like

https://cyberhus.dk/search/node/hej

The pagination at the bottom is missing. There are hundreds of results for this query.

The problems seems to be related to Views and the pager id. When disabling all views related module, the pager is back.

The issue has been noted by others before

e.g. https://knackforge.com/blog/sivaji/drupal-7-pager-not-visible-showing

and 

https://www.drupal.org/node/728734

**Comment by stefanospetrakis** [comment]
Some more related problem reports:

- https://www.drupal.org/node/1926720#comment-7784607
- https://www.drupal.org/node/1116542
- http://www.burgerboydaddy.com/blog/problem-views-pager
- http://drupal.stackexchange.com/questions/43809/views-page-not-showing-pager
- http://drupal.stackexchange.com/questions/43995/more-than-one-pager-in-the-same-page

**Comment by benjamin-dk** [comment]
Fixing issue by changing pager id manually in view, see 506923990cf89
